sonar.projectKey=Infomaniak_ios-authenticator
sonar.organization=infomaniak

sonar.sources=Authenticator,AuthenticatorCore,AuthenticatorCoreUI,AuthenticatorFeatures
sonar.exclusions=AuthenticatorResources,Scripts,Tuist,Project.swift,Debug-Frameworks,Derived